# Generated by Django 3.2.8 on 2021-12-07 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0007_auto_20211207_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='description_uz',
        ),
    ]
