# Generated by Django 3.2.8 on 2021-12-07 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0008_auto_20211207_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
