# Generated by Django 3.2.8 on 2021-12-07 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0009_auto_20211207_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255, null=True)),
                ('brand_image', models.ImageField(null=True, upload_to='equipments/brands')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='equipments.brand'),
        ),
    ]
