# Generated by Django 3.2.8 on 2021-12-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0010_auto_20211207_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='description_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='equipments/'),
        ),
    ]
