# Generated by Django 3.2.8 on 2022-01-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0012_auto_20220104_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='hourly_price',
            field=models.FloatField(null=True),
        ),
    ]
