# Generated by Django 3.2.8 on 2022-01-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0013_equipment_hourly_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='hourly_price_night',
            field=models.FloatField(null=True),
        ),
    ]
