# Generated by Django 3.2.8 on 2022-03-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0017_auto_20220303_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='gabarity_mm',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='moshnost_kvt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='shirina_ukladki',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='skorost_dvizheniya',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='skorost_ukladki',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='tip',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='tolshina_ukladki',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='ves',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='zagruzka_bunker',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
