# Generated by Django 3.2.8 on 2022-03-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0018_auto_20220303_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='hourly_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='hourly_price_night',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
