# Generated by Django 3.2.8 on 2022-02-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerprofile',
            name='bio',
        ),
    ]
