# Generated by Django 3.2.8 on 2022-01-06 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0003_renterproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
