# Generated by Django 3.2.8 on 2022-01-16 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0004_remove_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renterproduct',
            name='hourly_price',
        ),
    ]
