# Generated by Django 3.2.8 on 2022-01-29 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0007_auto_20220128_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
    ]
