# Generated by Django 3.2.8 on 2022-01-29 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0008_remove_profile_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='region',
        ),
    ]
