# Generated by Django 3.2.8 on 2022-02-10 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0014_equipment_hourly_price_night'),
        ('renter', '0010_auto_20220129_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='renterproduct',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipments.category'),
        ),
        migrations.AddField(
            model_name='renterproduct',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipments.subcategory'),
        ),
    ]
