# Generated by Django 3.2.8 on 2022-04-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0016_renterproduct_renter_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'erkak'), (2, 'ayol')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pochta_indexi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
