# Generated by Django 3.2.8 on 2021-12-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
