# Generated by Django 3.2.8 on 2022-01-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_user_activation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
