# Generated by Django 3.2.8 on 2022-02-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
