# Generated by Django 3.2.8 on 2022-04-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_user_fmc_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fmc_token_updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
