# Generated by Django 3.2.8 on 2022-01-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='customer_addresss',
            new_name='customer_address',
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
    ]
