# Generated by Django 3.2.8 on 2022-01-27 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20220127_0738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='region_of_country',
            old_name='Country',
            new_name='country',
        ),
    ]
