# Generated by Django 3.2.8 on 2022-01-27 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20220127_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='country',
            new_name='country_name',
        ),
        migrations.RenameField(
            model_name='region_of_country',
            old_name='region',
            new_name='region_name',
        ),
    ]
