# Generated by Django 3.2.8 on 2022-01-28 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0006_busytimes'),
        ('customer', '0005_auto_20220127_1020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Region_of_country',
            new_name='Region',
        ),
    ]
