# Generated by Django 3.2.8 on 2022-01-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_rename_region_of_country_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
