# Generated by Django 3.2.8 on 2022-02-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_region_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='customer_image',
            field=models.ImageField(null=True, upload_to='users'),
        ),
    ]
