# Generated by Django 3.2.8 on 2022-01-16 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0013_equipment_hourly_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('lat', models.CharField(max_length=255)),
                ('long', models.CharField(max_length=255)),
                ('order_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipments.equipment')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderChecking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checking_start', models.DateTimeField(auto_now_add=True)),
                ('checking_end', models.DateTimeField()),
                ('confirmed', models.IntegerField(choices=[(1, 'pending'), (2, 'canceled'), (3, 'accepted'), (4, 'no response')])),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipments.equipment')),
                ('oder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renter_temp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
