# Generated by Django 3.2.8 on 2022-04-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderchecking',
            name='confirmed',
            field=models.SmallIntegerField(choices=[(1, 'pending'), (2, 'canceled'), (3, 'accepted'), (4, 'no response')], max_length=255),
        ),
    ]
