# Generated by Django 3.2.8 on 2022-01-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
