# Generated by Django 3.2.8 on 2022-04-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_refreshfirebasetoken_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebasenotification',
            name='oreder_id',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
