# Generated by Django 3.2.8 on 2022-01-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_time',
            field=models.DateTimeField(),
        ),
    ]
