# Generated by Django 3.2.8 on 2022-04-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_firebasenotification_oreder_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebasenotification',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='refreshfirebasetoken',
            name='fmc_token',
            field=models.TextField(blank=True, default='string', null=True),
        ),
    ]
