# Generated by Django 3.2.8 on 2022-01-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
