# Generated by Django 3.2.8 on 2022-04-12 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20220412_0152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefreshFireBaseToken',
        ),
    ]
