# Generated by Django 3.2.8 on 2022-01-16 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0006_busytimes'),
        ('orders', '0005_alter_order_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderchecking',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renter.renterproduct'),
        ),
    ]
