# Generated by Django 3.2.8 on 2022-01-16 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderchecking_equipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderchecking',
            old_name='oder',
            new_name='order',
        ),
    ]
