# Generated by Django 3.2.8 on 2022-01-16 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0008_alter_order_renter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='renter',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='renter', to='index.user'),
        ),
    ]
