# Generated by Django 3.2.8 on 2022-01-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderchecking',
            name='confirmed',
            field=models.CharField(choices=[('pending', 'pending'), ('canceled', 'canceled'), ('accepted', 'accepted'), ('no_response', 'no response')], max_length=255),
        ),
    ]
