# Generated by Django 3.2.8 on 2022-02-02 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0015_auto_20220202_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderchecking',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter_temp', to=settings.AUTH_USER_MODEL),
        ),
    ]
