# Generated by Django 3.2.8 on 2022-02-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderchecking',
            name='confirmed',
            field=models.CharField(choices=[(1, 'pending'), (2, 'canceled'), (3, 'accepted'), (4, 'no response')], max_length=255),
        ),
    ]
