# Generated by Django 3.2.8 on 2022-03-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
