# Generated by Django 3.2.8 on 2022-03-30 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_alter_order_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.IntegerField(choices=[(1, 'CLICK'), (2, 'PAY_ME'), (3, 'APELSIN')], default=1),
        ),
    ]
