# Generated by Django 3.2.8 on 2022-03-30 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0018_auto_20220303_0953'),
        ('orders', '0023_alter_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='daylight_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='night_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='equipments.equipment'),
        ),
    ]
