# Generated by Django 3.2.8 on 2022-04-04 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_refreshfirebasetoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firebasenotification',
            old_name='boyd',
            new_name='body',
        ),
    ]
