# Generated by Django 3.2.8 on 2022-04-04 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_firebasenotification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firebasenotification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='refreshfirebasetoken',
            name='user',
        ),
    ]
