# Generated by Django 3.2.8 on 2022-04-04 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0029_auto_20220404_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebasenotification',
            name='user',
            field=models.ForeignKey(default=75, on_delete=django.db.models.deletion.CASCADE, to='index.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refreshfirebasetoken',
            name='user',
            field=models.ForeignKey(default=75, on_delete=django.db.models.deletion.CASCADE, to='index.user'),
            preserve_default=False,
        ),
    ]
