# Generated by Django 3.2.8 on 2022-04-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20220404_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebasenotification',
            name='image_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firebasenotification',
            name='oreder_id',
            field=models.IntegerField(default=111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firebasenotification',
            name='type_notification',
            field=models.IntegerField(choices=[(1, 'ACCEPTED'), (2, 'CANCELED'), (3, 'NO_RESPONSE')], default=3),
        ),
    ]
