# Generated by Django 3.2.8 on 2022-04-05 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0030_auto_20220404_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebasenotification',
            name='image_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firebasenotification',
            name='oreder_id',
            field=models.IntegerField(default=85),
        ),
        migrations.AddField(
            model_name='firebasenotification',
            name='type_notification',
            field=models.IntegerField(choices=[(1, 'ACCEPTED'), (2, 'CANCELED'), (3, 'NO_RESPONSE')], default=3),
        ),
        migrations.AlterField(
            model_name='firebasenotification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
