# Generated by Django 3.2.8 on 2022-04-06 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0032_alter_refreshfirebasetoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshfirebasetoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
