# Generated by Django 3.2.8 on 2022-04-05 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0017_auto_20220401_0603'),
        ('orders', '0032_auto_20220405_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firebasenotification',
            name='users',
        ),
        migrations.AddField(
            model_name='firebasenotification',
            name='its',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='renter.renterproduct'),
            preserve_default=False,
        ),
    ]
