# Generated by Django 3.2.8 on 2022-04-05 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0034_auto_20220405_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebasenotification',
            name='user',
            field=models.ForeignKey(default=75, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
