# Generated by Django 3.2.8 on 2022-04-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_alter_firebasenotification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firebasenotification',
            name='user',
        ),
        migrations.AddField(
            model_name='firebasenotification',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
