# Generated by Django 3.2.8 on 2022-04-05 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0037_auto_20220405_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firebasenotification',
            name='user_id',
        ),
        migrations.AddField(
            model_name='firebasenotification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
