# Generated by Django 3.2.8 on 2022-04-10 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_auto_20220405_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firebasenotification',
            name='image_url',
        ),
    ]
