# Generated by Django 3.2.8 on 2021-12-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255, null=True)),
                ('text', models.CharField(max_length=255, null=True)),
                ('sms_type', models.PositiveSmallIntegerField(choices=[(1, 'create_user'), (2, 'reset_password'), (3, 'notification'), (4, 'news')], default=1)),
                ('is_sent', models.PositiveSmallIntegerField(choices=[(0, 'not_sent'), (1, 'sent')], default=0)),
            ],
        ),
    ]
